[package]
name = "rs_compute"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
pyo3 = { version = "0.23.4", features = ["extension-module"] }

[lib]
name = "rs_compute"
crate-type = ["cdylib"]
